language: ruby
rvm:
- 2.0.0
- 2.1.1
bundler_args: --without development --path=~/.bundle
services:
- postgresql
- memcached
- redis-server
env:
  matrix:
  - ROOMRES_ADAPTER=postgresql ROOMRES_DB_PREFIX=roomres ROOMRES_DB_USERNAME=travis
    ROOMRES_DB_HOST=127.0.0.1
  global:
    - BUNDLE_ARCHIVE="RoomReservation"
    - AWS_S3_BUCKET="CI-Artifacts"
    - secure: kKORhtQCNWogqIsM6y20CcfQRFuB75PfIOA9geixEWOBDjhbJv2SGTKjbhOZW0BvP4j5FHY3lNQ+gOkmNUUBdlvImQWW+qqUOWswKlLs5KHHq1yUTg8WqnJzrex0fbPtUSgCr4jCsoyBPHCCvPleA6/1WLe79RU3TUXfzY0q9xU=
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundle_cache -v 0.1.0
  - bundle_cache_install
before_script:
  - psql -c 'create database roomres_test;' -U postgres
  - cp config/config.example.yml config/config.yml
after_script:
  - bundle_cache
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/ --format documentation
