day_limit:
  tag_attributes:
    type: number
  category: Reservation Settings
  default: 0
max_concurrent_reservations:
  tag_attributes:
    type: number
  category: Reservation Settings
  default: 0
reservation_email:
  tag_attributes:
    class: tinymce
  field_type: text_area
  category: Email Settings
  default: ''
cancellation_email:
  tag_attributes:
    class: tinymce
  field_type: text_area
  category: Email Settings
  default: ''
update_email:
  tag_attributes:
    class: tinymce
  field_type: text_area
  category: Email Settings
  default: ''
from_name:
  category: Email Settings
  default: 'Room Reservation System'
from_address:
  category: Email Settings
  default: 'no-reply@roomreservation.com'
email_reservation_subject:
  category: Email Settings
  default: 'Study Room Reservation'
email_cancellation_subject:
  category: Email Settings
  default: 'Study Room Reservations Cancellation'
email_update_subject:
  category: Email Settings
  default: 'Study Room Reservation Updated'
announcement_header_message:
  default: ''
reservation_padding:
  tag_attributes:
    type: number
  category: Reservation Settings
  default: 10
reservation_times:
  field_type: hash
  category: "User Reservation Limits (Minutes)"
  immune_keys:
    - admin
    - default
  default:
    graduate: 360
    faculty: 360
    professional: 360
    default: 180
    admin: 720